version: '2.1'

services:

  server:
    restart: always
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server:/server
      - ./image_uploads:/image_uploads
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG}
      - RDS_USERNAME=${RDS_USERNAME}
      - RDS_PASSWORD=${RDS_PASSWORD}
      - RDS_DB_NAME=${RDS_DB_NAME}
      - RDS_HOSTNAME=${RDS_HOSTNAME}
      - RDS_PORT=${RDS_PORT}
      - FLASK_APP=${FLASK_APP}
      - IMAGE_DIRECTORY=${IMAGE_DIRECTORY}
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:alpine
    environment:
      - RDS_USERNAME=${RDS_USERNAME}
      - RDS_PASSWORD=${RDS_PASSWORD}
      - RDS_DB_NAME=${RDS_DB_NAME}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - ${RDS_PORT}:${RDS_PORT}

#  client:
#    restart: always
#    build: ./client
#    ports:
#      - 80:80
#    volumes:
#      - .:/client
#    environment:
#      - NODE_ENV=${NODE_ENV}