version: '2.1'

services:

  server:
    restart: always
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - .:/server
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

#  client:
#    restart: always
#    build: ./client
#    ports:
#      - 80:80
#    volumes:
#      - .:/client
#    environment:
#      - NODE_ENV=${NODE_ENV}