version: '3.5'

services:

  server:
    container_name: metuo.server
    restart: always
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server:/server
      - ./image_uploads:/image_uploads
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_DEBUG=${FLASK_DEBUG}
      - RDS_USERNAME=${RDS_USERNAME}
      - RDS_PASSWORD=${RDS_PASSWORD}
      - RDS_DB_NAME=${RDS_DB_NAME}
      - RDS_HOSTNAME=${RDS_HOSTNAME}
      - RDS_PORT=${RDS_PORT}
      - IMAGE_DIRECTORY=${IMAGE_DIRECTORY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - PYTHON_ENV=${PYTHON_ENV}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - postgres

  postgres:
    container_name: metuo.postgres
    restart: always
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - ${RDS_PORT}:${RDS_PORT}
