version: '2.1'

services:

  server:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/server
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG}
    depends_on:
      - postgres
    entrypoint: ["flask", "run", "--host", "0.0.0.0"]

  postgres:
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
